---
- name: Add Bazel APT key
  become: true
  apt_key:
    url: https://bazel.build/bazel-release.pub.gpg 
    state: present
  
- name: Add Bazel APT repository 
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8
    state: present
    filename: bazel 