---
# Adds the Google APT key and the Chrome APT repository
#
# After this packages such as google-chrome-stable may be installed using apt
- name: Add Google APT key
  become: true
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub 
    state: present
  
- name: Add Google Chrome APT repository 
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
