---
# Adds the Spotify APT key and the Spotify APT repository
#
# After this the spotify package may be installed using apt
- name: Download and dearmor Spotify APT key
  block:
    - name: Download Spotify GPG key
      get_url:
        url: https://download.spotify.com/debian/pubkey_5384CE82BA52C83A.asc
        dest: /tmp/spotify.asc
        mode: '0644'

- name: Dearmor GPG key and save to trusted.gpg.d
  become: true
  shell: gpg --dearmor < /tmp/spotify.asc > /etc/apt/trusted.gpg.d/spotify.gpg
  args:
    creates: /etc/apt/trusted.gpg.d/spotify.gpg

- name: Add Spotify APT repository
  become: true
  apt_repository:
    repo: deb https://repository.spotify.com stable non-free
    state: present
    filename: spotify
