  - name: Build zoom
    tags: 
      - deb
    command: "bazel build //package/zoom:zoom_deb"
    # This task never make modification to the system, so do not mark it as a change 
    changed_when: false 

  - name: Install zoom
    become: true
    tags: 
      - deb
    apt:
      deb: "../bazel-bin/package/zoom/zoom.deb"