---
- name: Setup system for building the monorepo 
  hosts: local
  tasks:
  - include_tasks: tasks/bazel.yml

  - name: Install APT Packages
    become: true
    apt:
      update_cache: true
      cache_valid_time: 3600
      pkg:
      - bazel
      - default-jdk