---
- name: Set up living room speaker 
  hosts: speaker
  become: true
  handlers:
  - name: restart spotifyd 
    ansible.builtin.systemd:
      state: restarted
      name: spotifyd
  tasks:
  - name: Add authorized SSH Keys
    ansible.posix.authorized_key:
      user: daan
      state: present
      key: "{{ item }}"
    with_file:
      - /home/daan/.ssh/id_rsa.pub
      - /home/daan/.ssh/id_ed25519.pub

  - name: Delete password set for 'daan' during installation 
    ansible.builtin.user:
      name: daan
      password: ''

  - name: Make sure 3.5mm jack audio out is not enabled
    ansible.builtin.lineinfile:
      path: /boot/config.txt
      state: absent
      regexp: 'dtparam=audio=on'

  - name: Ensure audio over HDMI is turned off
    ansible.builtin.lineinfile:
      path: /boot/config.txt
      regexp: '^dtoverlay=vc4-kms-v3d'
      line: dtoverlay=vc4-kms-v3d,audio=off

  - name: Enable hifiberry dac overlay
    ansible.builtin.lineinfile:
      path: /boot/config.txt
      regexp: '^dtoverlay=hifiberry-dac'
      line: dtoverlay=hifiberry-dac

  - name: Create alsa config
    ansible.builtin.copy:
      content: |
        pcm.!default {
          type hw card 0
        }
        ctl.!default {
          type hw card 0
        }
      dest: /etc/asound.conf

  - name: Upgrade packages
    apt:
      upgrade: dist
      update_cache: yes
      cache_valid_time: 3600

  - name: Install base packages
    apt:
      pkg:
      - vim-nox

  - name: Install spotifyd
    ansible.builtin.unarchive:
      src: https://github.com/Spotifyd/spotifyd/releases/download/v0.3.5/spotifyd-linux-armv6-slim.tar.gz 
      dest: /usr/bin
      remote_src: yes

  - name: Create spotifyd service 
    ansible.builtin.copy:
      src: spotifyd.service 
      dest: /etc/systemd/system/spotifyd.service
      owner: root
      group: root
      mode: '0755'

  - name: Enable the spotifyd service 
    ansible.builtin.systemd:
      state: started
      enabled: true
      daemon_reload: true
      name: spotifyd