name: Build and test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    container: ghcr.io/wildarch/mono:ci
    env:
      GITHUB_WORKSPACE: /home/ubuntu
    steps:
      - uses: actions/checkout@v4
      - run: |
          cmake -S experiments/columnar -B /tmp/build -G Ninja \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_CXX_COMPILER=clang++-20  \
              -DCMAKE_LINKER_TYPE=MOLD \
      - run: cmake --build /tmp/build --target check

